### ISSUE TITLE
Slow syntax highlighting

### ISSUE THREAD

**Issue by leapofazzam123** [AmrDeveloper/CodeView#3]

**Comment by AmrDeveloper** [comment]
Hello @leapofazzam123 can you provide more details or your config code so we can know where is the problem

**Comment by leapofazzam123** [comment]
I see the preview gif and the syntax highlighting is very slow

**Comment by AmrDeveloper** [comment]
Thanks for your feedback, 

The delay on screenshots isn't because the highlighter is slow, but it's because I made it start highlighting after the user stop typing.

I added a new option so you can control if you want to highlight while the user is typing or after he finishes.

Check the new screenshots, you are welcome to add feature request or bug report any time

Thanks
Amr Hesham
